name: Release

on:
  push:
    tags:
      - 'v[0-9]*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew upgrade
      - run: brew install shfmt shellcheck
      - name: Install shellspec
        run: |
          echo "${HOME}/.local/bin" >> "$GITHUB_PATH"
          curl -fsSL https://git.io/shellspec | sh -s master -y
      - name: Make dist archive
        run: make dist MINIFY=1
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: ${{ contains(github.ref, '-') }}
      - name: Upload tar.gz archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: shdotenv.tar.gz
          asset_name: shdotenv.tar.gz
          asset_content_type: application/gzip
      - name: Upload executable script
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: shdotenv
          asset_name: shdotenv
          asset_content_type: application/gzip
